### ISSUE TITLE
No Update functionality

### ISSUE THREAD

**Issue by Mr-Headrick** [AmazingAJ10/subs5#4]
from collection after clicking on ellipsis, it goes to an update form but the existing object data is not populated in the form (it looks like the create form with dim 'default' suggestions in fields.

The update button does not do anything.

**Comment by AmazingAJ10** [comment]
The update function does not do anything, I set to it to Update Existing in UI Library, but it does nothing. This is one of my next fixes that I will work on this week.

**Comment by ghost** [comment]
Watch the videos about edit/update!

**Comment by AmazingAJ10** [comment]
The edit page now allows you to make changes to the subscription, so that it a step in the right direction and I'm glad that this is finally working. However, the old information does not populate on the edit screen, so you have to type it again, as opposed to just changing something in order to make an update. For this reason, I am closing this issue as there is update functionality and opening a new one to make the old information populate on the edit screen,
